# Basic
title = "Valen Yamamoto"
baseURL = "https://ValenYamamoto.github.io"
theme = "vno"

# supported languages: en-us, zh-cn (lowercase language codes only)
defaultContentLanguage = 'en-us'
# here lists available languages, if you wish to add your own custom translation, please refer to https://gohugo.io/content-management/multilingual
[languages]
  [languages.en-us]
    languageName = 'English(United States)'
    weight = 10
  [languages.zh-cn]
    languageName = '简体中文（中国大陆）'
    weight = 20

# Pagination
paginate = 20
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "About Me"
    identifier = "aboutme"
    url = "/2022/11/about-me/"
    weight = 10
  [[menu.main]]
    name = "Projects"
    identifier = "projects"
    url = "/2022/11/projects/"
    weight = 10

    
[params]
author = "Valen Yamamoto"
subtitle = "CS Student @ UCI"
description = "Welcome to my portfolio!"
welcomeMessage = "Hi! I am a computer science student at the University of California, Irvine specializing in machine learning, robotics algorithms, and optimizing parallel algorithms for high performance environments"

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = "blue"

[params.comment]
disqus = "vno-hugo"
duoshuo = ""

# Take a look on https://github.com/gitalk/gitalk#usage for more info.
[params.comment.gitalk]
ID = ""
secret = ""
repo = ""
owner = ""

[params.social]
github = "ValenYamamoto"
mail = "vyamamot@uci.edu"
linkedin = "valen-yamamoto"

[params.ga]
ID = "your_ga_id"
host = "your_host"

# The blog button should not be removed.
[params.blogButton]
title = "Blog"
description = "Visit blog"

[params.copyright]
license = 'CC BY-NC-SA 4.0'
license_link = 'http://creativecommons.org/licenses/by-nc-sa/4.0/'

[permalinks]
posts = "/:year/:month/:title/"
